[package]
name = "dirt-common"
version = "0.1.0"
edition.workspace = true

license.workspace = true

[features]
default = []
user = ["aya"]
ebpf = ["aya-ebpf"]

[dependencies]
aya = { workspace = true, optional = true }
aya-ebpf = { workspace = true, optional = true }

[lib]
path = "src/lib.rs"
